controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

test:
    path: /test
    controller: App\Controller\api\test\event\TestController::test